import Head from 'next/head'
import { useContext, useEffect, useState } from 'react';
import { Chat } from '@/components/home/chat/Chat';
import { Authenticate } from '@/components/home/Authenticate/authenticate';
import { ChatContext } from '@/contexts/context';
import { getToken } from '@/services/Auth';
import { api } from '@/services/Axios';
import { Loading } from '@/components/UseFul/Loading';


  
export default function Home() {
const { chat, setChat, setName, setUserID } = useContext(ChatContext);


const getAuth = async () => {

  if(getToken()){

    const user = await api.get("/auth")

    if (!user.data.sucess) {
      return setChat(false)
    }

    setName(user.data.user.nome);
    setUserID(user.data.user.id);

    setChat(true);
  }
}


  useEffect( () => {
    getAuth();
  }, [])
  

  return (
    <>
      <Head>
        <title>Teste Bluelab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       { chat ?  <Chat /> : <Authenticate /> }
  
    </>
  )
}