import Head from 'next/head'
import io from 'socket.io-client'
import { useState } from 'react';
import { Chat } from '@/components/Chat';
import axios from 'axios';
import { Header } from '@/components/Header';



const socket = io("http://localhost:3333");

export default function Home() {
  const [cpf, setCpf] = useState('');
  const [name, setName] = useState('');
  const [chat, setChat] = useState(false);
  const [cpfValid, setCpfValid] = useState(true);
  const [serverMessage, setServerMessage] = useState('');

 const room = "123"

  const getCliente = async () =>{
    event?.preventDefault();
    const cliente = await axios({
      url: "http://localhost:3333/cliente",
      method: "put",
      data:{cpf:cpf}
    });
    
    if(cliente.data.sucess){
      setName(cliente.data.cliente.nome);  
      joinRoom();
    }

    setCpfValid(cliente.data.sucess);
    setServerMessage(cliente.data.mensagem)
  }

  const joinRoom = () => {
    if (cpf !== '') {
      socket.emit('joinRoom', { room: room, name: name });
      setChat(true);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {chat ? 
      <Chat socket={socket} name={name} room={room} /> 
      :  
      <main className="bg-white max-w-lg mx-auto p-8 md:p-12 my-10 rounded-lg shadow-2xl">

        <Header title='Welcome to a BlueLab teste' span='Sign in to your chat.'/>

        <section className="mt-10">
          {
          cpfValid ? 
          <div></div> 
          : 
          <div className='text-center bg-red-400'>
          <p className="text-white mb-2"> {serverMessage}</p>
          </div>
          } 

            <form className="flex flex-col" method="POST" action="#">
                <div className="mb-6 pt-3 rounded bg-gray-200">
                    <label className="block text-gray-700 text-sm font-bold mb-2 ml-3" htmlFor="email">Cpf</label>
                    <input  onChange={({ target }) => { setCpf(target.value) }} type="text" id="cpf" className="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3"/>
                </div>
                <div className="flex justify-end">
                    <a href="http://localhost:3000/CreateAccount" className="text-sm text-purple-600 hover:text-purple-700 hover:underline mb-6">Create account</a>
                </div>
                <button onClick={getCliente} className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 rounded shadow-lg hover:shadow-xl transition duration-200" type="submit">Sign In</button>
            </form>
        </section> 
      </main>}
     
    </>
  )
}
